### ISSUE TITLE
check it

### ISSUE THREAD

**Issue by jaypatel1s** [jay-gami/execrise1#1]
class Divisible

    def divide
      n1,n2,n3 = gets.chomp.split.map(&:to_i)
      range=(n1..n2)
n=0
         (range).each do |j|
        if j%n3==0
            print "#{j} "  
            while(n!=0)
                n=n/10  
                count++
            end
        end
    end
    #  for i in range do
    #    if (i%n3)==0
    
    #     print "#{i}"

    #    end
    #  end
   
    end

end
obj=Divisible.new()
obj.divide

**Comment by jay-gami** [comment]
ok
